import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Animated,
  Easing,
  Pressable,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  View,
} from 'react-native';

// V0.29 — PROGRESSION & BALANCE PASS
// Original temporary art + own React Native implementation.
// Main goals: calmer parking balance, many more meaningful upgrades, visible milestones.

const SAVE_KEY = 'rail-rush-hour-v029';
const LEGACY_KEY = 'rail-rush-hour-v028';
const TICK = 1000;
const MAX_FACILITY_LEVEL = 15;
const MAX_STATION_LEVEL = 10;

const money = (v) => `€${Math.max(0, Math.round(v)).toLocaleString('nl-NL')}`;
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const upgradeCost = (base, currentLevel, growth = 1.31) => Math.round(base * Math.pow(growth, Math.max(0, currentLevel)));
const xpNeed = (stationLevel) => 5 + stationLevel * 3;

const ROUTES = [
  { id: 'north', name: 'Northbridge', code: 'A', color: '#55d997', fare: 6, unlock: 1 },
  { id: 'sea', name: 'Seabright', code: 'B', color: '#48a8ff', fare: 9, unlock: 3 },
  { id: 'ember', name: 'Emberfall', code: 'C', color: '#b879ff', fare: 14, unlock: 5 },
  { id: 'harbor', name: 'Harbor Point', code: 'D', color: '#ff9d52', fare: 18, unlock: 7 },
  { id: 'capital', name: 'Grand City', code: 'E', color: '#ff7186', fare: 25, unlock: 9 },
];

const STAGES = [
  ['Small Station', '1 platform • local traffic'],
  ['Local Hub', 'café • signage • more upgrades'],
  ['Town Station', 'second route • shop • cleaning'],
  ['Growing Junction', '2 platforms • longer trains'],
  ['Regional Station', 'third route • toilets'],
  ['Regional Hub', 'restaurant • larger concourse'],
  ['Major Station', 'Harbor route • 3-set trains'],
  ['Intercity Hub', '3 platforms • simultaneous traffic'],
  ['Metropolitan', 'Grand City • premium facilities'],
  ['Grand Terminal', 'manager automation • full station'],
];

const FACILITIES = {
  parking: { title: 'Parking', icon: 'P', base: 110, unlock: 1 },
  entrance: { title: 'Entrance', icon: '⇥', base: 140, unlock: 1 },
  ticket: { title: 'Tickets', icon: '🎫', base: 160, unlock: 1 },
  security: { title: 'Security', icon: '◆', base: 190, unlock: 1 },
  waiting: { title: 'Waiting Hall', icon: '▰', base: 220, unlock: 1 },
  platform: { title: 'Platforms', icon: 'Ⅱ', base: 300, unlock: 1 },
  train: { title: 'Train', icon: '▣', base: 450, unlock: 1 },
  signage: { title: 'Signage', icon: '↗', base: 250, unlock: 2 },
  cafe: { title: 'Café', icon: '☕', base: 280, unlock: 2 },
  shop: { title: 'Shop', icon: '▦', base: 360, unlock: 3 },
  cleaning: { title: 'Cleaning', icon: '✦', base: 420, unlock: 3 },
  toilet: { title: 'Toilets', icon: 'WC', base: 480, unlock: 4 },
  restaurant: { title: 'Restaurant', icon: '🍴', base: 700, unlock: 6 },
  vip: { title: 'VIP', icon: '★', base: 950, unlock: 7 },
  manager: { title: 'Manager', icon: 'M', base: 1600, unlock: 10 },
};

const MILESTONES = {
  parking: { 3:'EXTRA PARKING ROW',6:'P+R ZONE',9:'COVERED PARKING',12:'PARKING DECK',15:'SMART PARKING' },
  entrance: { 3:'DOUBLE DOORS',6:'WIDE GATES',9:'FLOW PLAZA',12:'SMART GATES',15:'GRAND ENTRANCE' },
  ticket: { 3:'EXTRA MACHINES',6:'MOBILE TICKETING',9:'FAST LANE',12:'AUTO BANK',15:'SMART TICKETING' },
  security: { 3:'SECOND LANE',6:'FAST SCAN',9:'AUTO GATES',12:'EXPRESS LANE',15:'SEAMLESS CHECK' },
  waiting: { 3:'SEATING WING',6:'INFO ZONE',9:'LOUNGE',12:'QUIET ZONE',15:'GRAND HALL' },
  platform: { 3:'FULL CANOPY',6:'BOARDING ZONES',9:'WIDE PLATFORM',12:'DIGITAL SIGNS',15:'HIGH CAPACITY' },
  train: { 3:'LONGER STOCK',6:'POWER DOORS',9:'HIGH CAPACITY CARS',12:'PREMIUM CONSIST',15:'FLAGSHIP TRAIN' },
  signage: { 3:'LIVE BOARDS',6:'WAYFINDING',9:'SMART ROUTING',12:'CROWD GUIDANCE',15:'PREDICTIVE FLOW' },
  cafe: { 3:'SECOND COUNTER',6:'BAKERY',9:'FOOD COURT',12:'MOBILE ORDER',15:'STATION CAFÉ+' },
  shop: { 3:'BIGGER STORE',6:'NEWS KIOSK',9:'TRAVEL SHOP',12:'EXPRESS CHECKOUT',15:'RETAIL ARCADE' },
  cleaning: { 3:'CLEANING CREW',6:'QUICK RESPONSE',9:'ZONE TEAMS',12:'SMART CLEANING',15:'SPOTLESS STATION' },
  toilet: { 3:'EXTRA BLOCK',6:'FAMILY AREA',9:'ACCESSIBLE+',12:'SMART SERVICE',15:'PREMIUM FACILITY' },
  restaurant: { 3:'HOT KITCHEN',6:'MORE SEATING',9:'TABLE SERVICE',12:'EXPRESS MENU',15:'DINING HALL' },
  vip: { 3:'VIP SEATING',6:'LOUNGE BAR',9:'QUIET ROOMS',12:'PRIORITY SERVICE',15:'PREMIUM CLUB' },
  manager: { 3:'AUTO DEPART+',6:'CROWD ASSIST',9:'SMART DISPATCH',12:'SHIFT CONTROL',15:'FULL AUTOMATION' },
};

const GOALS = [
  ['parking',3,'Reach Parking Lv 3',350],
  ['entrance',3,'Reach Entrance Lv 3',450],
  ['ticket',3,'Reach Tickets Lv 3',550],
  ['served',150,'Transport 150 passengers',800],
  ['station',3,'Reach Station Level 3',1000],
  ['security',6,'Reach Security Lv 6',1400],
  ['departures',12,'Complete 12 departures',1800],
  ['station',5,'Reach Station Level 5',2600],
  ['served',2500,'Transport 2,500 passengers',4500],
  ['station',8,'Reach Station Level 8',7000],
];

function loadSave() {
  try {
    if (!globalThis?.localStorage) return null;
    const current = globalThis.localStorage.getItem(SAVE_KEY);
    if (current) return JSON.parse(current);
    const legacy = globalThis.localStorage.getItem(LEGACY_KEY);
    return legacy ? JSON.parse(legacy) : null;
  } catch { return null; }
}
function saveGame(data) {
  try { if (globalThis?.localStorage) globalThis.localStorage.setItem(SAVE_KEY, JSON.stringify(data)); } catch {}
}
function routeById(id) { return ROUTES.find(r=>r.id===id)||ROUTES[0]; }
function makeService(platform, routeId, sets=1) { return { platform,routeId,sets,phase:'arriving',countdown:2,delay:0,hold:0,onboard:0 }; }
function parkingCapacity(lv){ const n=Math.max(1,lv); return 110+(n-1)*70+Math.floor((n-1)/3)*35; }
function entranceCapacity(lv){ return 55+(Math.max(1,lv)-1)*35; }
function ticketCapacity(lv){ return 48+(Math.max(1,lv)-1)*30; }
function securityCapacity(lv){ return 44+(Math.max(1,lv)-1)*28; }
function waitingCapacity(lv,stationLevel){ return 110+(Math.max(1,lv)-1)*60+(stationLevel-1)*20; }
function platformCapacity(lv,platforms){ return (100+(Math.max(1,lv)-1)*55)*platforms; }
function trainCapacity(service,levels,stationLevel){ return (120+Math.max(1,levels.train)*70+(stationLevel-1)*20)*service.sets; }
function milestone(kind,level){ return MILESTONES[kind]?.[level]||null; }
function nextMilestone(kind,level){ const keys=Object.keys(MILESTONES[kind]||{}).map(Number).filter(x=>x>level).sort((a,b)=>a-b); return keys[0]?{level:keys[0],name:MILESTONES[kind][keys[0]]}:null; }
function effectFor(kind,nextLevel){
  if(kind==='parking') return `+${parkingCapacity(nextLevel)-parkingCapacity(Math.max(1,nextLevel-1))} spaces`;
  if(kind==='entrance') return '+3 entry pax/s';
  if(kind==='ticket') return '+3 ticket pax/s';
  if(kind==='security') return '+3 security pax/s';
  if(kind==='waiting') return '+60 hall capacity';
  if(kind==='platform') return '+55 platform capacity';
  if(kind==='train') return '+70 seats / set';
  if(kind==='signage') return '+2 routing pax/s';
  if(kind==='cafe') return '+€3 / sec';
  if(kind==='shop') return '+€4 / sec';
  if(kind==='cleaning') return '+ satisfaction recovery';
  if(kind==='toilet') return '+ comfort recovery';
  if(kind==='restaurant') return '+€7 / sec';
  if(kind==='vip') return '+ departure bonus';
  if(kind==='manager') return '+ faster automation';
  return '+ capacity';
}

function HudTile({label,children,wide}){ return <View style={[styles.hudTile,wide&&styles.hudWide]}><Text style={styles.hudLabel}>{label}</Text>{children}</View>; }
function MiniPeople({count,color='#48a8ff',max=12}){
  const shown=Math.min(max,Math.ceil(Math.max(0,count)/6));
  return <View style={styles.peopleRow}>{Array.from({length:shown}).map((_,i)=><View key={i} style={styles.person}><View style={styles.personHead}/><View style={[styles.personBody,{backgroundColor:i%3===0?color:i%3===1?'#df7856':'#6879a5'}]}/></View>)}</View>;
}
function MovingDot({delay=0,duration=2800,color='#f3c596',from,to}){
  const p=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.delay(delay),Animated.timing(p,{toValue:1,duration,easing:Easing.linear,useNativeDriver:true}),Animated.timing(p,{toValue:0,duration:0,useNativeDriver:true})]));loop.start();return()=>loop.stop();},[delay,duration,p]);
  return <Animated.View style={[styles.movingDot,{backgroundColor:color,transform:[{translateX:p.interpolate({inputRange:[0,1],outputRange:[from[0],to[0]]})},{translateY:p.interpolate({inputRange:[0,1],outputRange:[from[1],to[1]]})}],opacity:p.interpolate({inputRange:[0,.08,.9,1],outputRange:[0,1,1,0]})}]}/>;
}
function Flow({active,from,to,color='#f3c596',count=4}){ if(!active)return null; return <View pointerEvents="none" style={StyleSheet.absoluteFill}>{Array.from({length:count}).map((_,i)=><MovingDot key={i} delay={i*220} duration={2500+(i%2)*350} color={i%3===0?color:i%3===1?'#e78a66':'#6d85ae'} from={[from[0]+(i%2)*3,from[1]+(i%2)*2]} to={[to[0]+(i%3)*3,to[1]+(i%2)*3]}/>)}</View>; }
function DoorPair({open}){
  const v=useRef(new Animated.Value(open?1:0)).current;
  useEffect(()=>{Animated.timing(v,{toValue:open?1:0,duration:350,useNativeDriver:true}).start();},[open,v]);
  return <View style={styles.doorPocket}><Animated.View style={[styles.doorLeaf,{transform:[{translateX:v.interpolate({inputRange:[0,1],outputRange:[0,-5]})}]}]}/><Animated.View style={[styles.doorLeaf,{right:0,transform:[{translateX:v.interpolate({inputRange:[0,1],outputRange:[0,5]})}]}]}/></View>;
}
function TrainGraphic({service,top,pulse}){
  const route=routeById(service.routeId),sets=clamp(service.sets,1,3),width=132+(sets-1)*55;
  const move=useRef(new Animated.Value(service.phase==='arriving'?1:0)).current;const prev=useRef(service.phase);
  useEffect(()=>{const old=prev.current;prev.current=service.phase;if(service.phase==='arriving'){move.setValue(1);Animated.timing(move,{toValue:0,duration:1200,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();}else if(service.phase==='departing'){move.setValue(0);Animated.timing(move,{toValue:-1,duration:1400,easing:Easing.in(Easing.cubic),useNativeDriver:true}).start();}else if(old==='away'&&service.phase==='boarding'){move.setValue(0);}},[service.phase,move]);
  if(service.phase==='away')return null;
  const x=move.interpolate({inputRange:[-1,0,1],outputRange:[-340,0,340]}),ready=service.phase==='ready',doorsOpen=['boarding','holding'].includes(service.phase),opacity=ready?pulse.interpolate({inputRange:[0,1],outputRange:[.78,1]}):1;
  return <Animated.View style={[styles.trainWrap,{top,width,opacity,transform:[{translateX:x},{rotateZ:'-2deg'}]}]}><View style={[styles.trainShadow,{width:width-6}]}/><View style={[styles.trainBody,{width,borderColor:ready?'#ffd25b':'#ccd7da'}]}><View style={[styles.trainNose,{backgroundColor:route.color}]}/><View style={styles.cabGlass}/><View style={[styles.routeStripe,{backgroundColor:route.color}]}/>{Array.from({length:sets}).map((_,s)=>{const l=34+s*55;return <React.Fragment key={s}><View style={[styles.carJoint,{left:l-2}]}/><View style={[styles.carWindow,{left:l+3}]}/><View style={[styles.carWindow,{left:l+18}]}/><View style={[styles.carWindow,{left:l+33}]}/><View style={[styles.doorSlot,{left:l+43}]}><DoorPair open={doorsOpen}/></View><View style={[styles.bogie,{left:l+5}]}/><View style={[styles.bogie,{left:l+32}]}/></React.Fragment>;})}<View style={styles.trainRoof}/></View></Animated.View>;
}
function ServiceCard({service,levels,stationLevel,waiting,priority,onPriority,onWait,onDepart}){
  const route=routeById(service.routeId),capacity=trainCapacity(service,levels,stationLevel),ready=service.phase==='ready';
  const state=service.phase==='arriving'?'ARRIVING':service.phase==='departing'?'DEPARTING':service.phase==='away'?`RETURN ${service.countdown}s`:service.phase==='holding'?`HOLD ${service.hold}s`:ready?`READY +${service.delay}s`:`BOARDING ${service.countdown}s`;
  return <View style={[styles.serviceCard,{borderTopColor:route.color},ready&&styles.serviceReady]}><View style={styles.serviceHead}><View style={[styles.routeBadge,{backgroundColor:route.color}]}><Text style={styles.routeBadgeText}>{route.code}{service.platform}</Text></View><View style={{flex:1}}><Text style={styles.serviceName}>{route.name}</Text><Text style={[styles.serviceState,ready&&styles.readyText]}>{state}</Text></View><Pressable onPress={onPriority} style={[styles.priority,priority&&styles.priorityOn]}><Text style={styles.priorityText}>★</Text></Pressable></View><View style={styles.metaRow}><Text style={styles.metaText}>{service.onboard}/{capacity}</Text><Text style={styles.metaText}>{waiting} waiting</Text><Text style={styles.metaText}>{service.sets} set{service.sets>1?'s':''}</Text></View><View style={styles.progress}><View style={[styles.progressFill,{width:`${Math.round(clamp(service.onboard/Math.max(1,capacity),0,1)*100)}%`,backgroundColor:route.color}]}/></View>{ready?<View style={styles.actions}><Pressable onPress={onWait} style={styles.waitBtn}><Text style={styles.actionText}>+5s WAIT</Text></Pressable><Pressable onPress={onDepart} style={styles.departBtn}><Text style={styles.actionText}>DEPART</Text></Pressable></View>:null}</View>;
}
function UpgradeCard({kind,level,stationLevel,cash,hot,onPress}){
  const spec=FACILITIES[kind],locked=stationLevel<spec.unlock,capped=level>=MAX_FACILITY_LEVEL,next=Math.max(1,level+1),price=upgradeCost(spec.base,level),canBuy=!locked&&!capped&&cash>=price,mile=milestone(kind,next),future=nextMilestone(kind,level);
  return <View style={[styles.upgradeCard,hot&&styles.upgradeHot,mile&&styles.upgradeMilestone,locked&&styles.locked]}><View style={styles.upIcon}><Text style={styles.upIconText}>{spec.icon}</Text></View><Text style={styles.upTitle}>{spec.title}</Text><Text style={styles.upLevel}>{locked?`UNLOCK ST ${spec.unlock}`:capped?'MAX':`LV ${level} → ${next}`}</Text><Text style={styles.upEffect}>{locked?'':capped?'FULLY BUILT':effectFor(kind,next)}</Text>{!locked&&!capped?<Text style={[styles.nextMilestone,mile&&styles.nextMilestoneNow]}>{mile?`★ ${mile}`:future?`Lv${future.level}: ${future.name}`:'FINAL TIER'}</Text>:null}<Pressable disabled={!canBuy} onPress={onPress} style={[styles.buyBtn,canBuy&&styles.buyReady,mile&&canBuy&&styles.buyMilestone]}><Text style={styles.buyText}>{locked?'LOCKED':capped?'MAX':money(price)}</Text></Pressable></View>;
}
function SideButton({label,icon,badge,active,onPress}){return <Pressable onPress={onPress} style={[styles.sideBtn,active&&styles.sideBtnOn]}><Text style={styles.sideIcon}>{icon}</Text><Text style={styles.sideLabel}>{label}</Text>{badge?<View style={styles.sideBadge}><Text style={styles.sideBadgeText}>{badge}</Text></View>:null}</Pressable>;}
function Panel({title,onClose,children}){return <View style={styles.panelShade}><View style={styles.panel}><View style={styles.panelHead}><Text style={styles.panelTitle}>{title}</Text><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>{children}</View></View>;}

export default function AppV29(){
  const saved=useRef(loadSave()).current;
  const initialLevels={
    parking:saved?.levels?.parking??1,entrance:saved?.levels?.entrance??1,ticket:saved?.levels?.ticket??1,security:saved?.levels?.security??1,waiting:saved?.levels?.waiting??1,platform:saved?.levels?.platform??1,train:saved?.levels?.train??1,
    signage:saved?.levels?.signage??0,cafe:saved?.levels?.cafe??0,shop:saved?.levels?.shop??0,cleaning:saved?.levels?.cleaning??0,toilet:saved?.levels?.toilet??0,restaurant:saved?.levels?.restaurant??0,vip:saved?.levels?.vip??0,manager:saved?.levels?.manager??0,
  };
  const [phase,setPhase]=useState('menu'),[cash,setCash]=useState(saved?.cash??1400),[gems]=useState(saved?.gems??18),[levels,setLevels]=useState(initialLevels),[stationLevel,setStationLevel]=useState(saved?.stationLevel??1),[developmentXP,setDevelopmentXP]=useState(saved?.developmentXP??0),[devLevel,setDevLevel]=useState(null);
  const [parkingQ,setParkingQ]=useState(12),[entranceQ,setEntranceQ]=useState(3),[ticketQ,setTicketQ]=useState(2),[securityQ,setSecurityQ]=useState(1),[waitingQ,setWaitingQ]=useState(5);
  const [demand,setDemand]=useState(Object.fromEntries(ROUTES.map(r=>[r.id,r.id==='north'?10:0]))),[services,setServices]=useState([makeService(1,'north',1)]),[priorityPlatform,setPriorityPlatform]=useState(1);
  const [served,setServed]=useState(saved?.served??0),[departures,setDepartures]=useState(saved?.departures??0),[lost,setLost]=useState(saved?.lost??0),[satisfaction,setSatisfaction]=useState(saved?.satisfaction??90),[clock,setClock]=useState(0),[goalIndex,setGoalIndex]=useState(saved?.goalIndex??0),[panel,setPanel]=useState(null),[message,setMessage]=useState('Parking is calmer now. Build the whole passenger chain.'),[flash,setFlash]=useState('');

  const pulse=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:850,easing:Easing.inOut(Easing.quad),useNativeDriver:false}),Animated.timing(pulse,{toValue:0,duration:850,easing:Easing.inOut(Easing.quad),useNativeDriver:false})]));loop.start();return()=>loop.stop();},[pulse]);

  const effectiveLevel=devLevel??stationLevel,stage=STAGES[effectiveLevel-1],unlockedRoutes=ROUTES.filter(r=>r.unlock<=effectiveLevel),platformsUnlocked=effectiveLevel>=8?3:effectiveLevel>=4?2:1,maxSets=effectiveLevel>=7?3:effectiveLevel>=4?2:1,rush=(clock%90)>=70;
  const parkingCap=parkingCapacity(levels.parking),entranceCap=entranceCapacity(levels.entrance),ticketCap=ticketCapacity(levels.ticket),securityCap=securityCapacity(levels.security),waitingCap=waitingCapacity(levels.waiting,effectiveLevel),platformCap=platformCapacity(levels.platform,platformsUnlocked),totalPlatform=Object.values(demand).reduce((a,b)=>a+b,0),fullestTrain=services.reduce((m,s)=>Math.max(m,s.onboard/Math.max(1,trainCapacity(s,levels,effectiveLevel))),0);
  const pressures=[['PARKING',parkingQ/parkingCap,'parking'],['ENTRANCE',entranceQ/entranceCap,'entrance'],['TICKETS',ticketQ/ticketCap,'ticket'],['SECURITY',securityQ/securityCap,'security'],['WAITING',waitingQ/waitingCap,'waiting'],['PLATFORMS',totalPlatform/platformCap,'platform'],['TRAINS',fullestTrain,'train']].sort((a,b)=>b[1]-a[1]),bottleneck=pressures[0],bottleneckPct=Math.round(bottleneck[1]*100);
  const xpRequired=xpNeed(stationLevel),xpPct=Math.round(clamp(developmentXP/xpRequired,0,1)*100);

  const cashRef=useRef(cash),levelsRef=useRef(levels),stationLevelRef=useRef(stationLevel),developmentRef=useRef(developmentXP),parkingRef=useRef(parkingQ),entranceRef=useRef(entranceQ),ticketRef=useRef(ticketQ),securityRef=useRef(securityQ),waitingRef=useRef(waitingQ),demandRef=useRef(demand),servicesRef=useRef(services),priorityRef=useRef(priorityPlatform),servedRef=useRef(served),departuresRef=useRef(departures),lostRef=useRef(lost),satRef=useRef(satisfaction),clockRef=useRef(clock);
  useEffect(()=>{cashRef.current=cash;},[cash]);useEffect(()=>{levelsRef.current=levels;},[levels]);useEffect(()=>{stationLevelRef.current=stationLevel;},[stationLevel]);useEffect(()=>{developmentRef.current=developmentXP;},[developmentXP]);useEffect(()=>{parkingRef.current=parkingQ;},[parkingQ]);useEffect(()=>{entranceRef.current=entranceQ;},[entranceQ]);useEffect(()=>{ticketRef.current=ticketQ;},[ticketQ]);useEffect(()=>{securityRef.current=securityQ;},[securityQ]);useEffect(()=>{waitingRef.current=waitingQ;},[waitingQ]);useEffect(()=>{demandRef.current=demand;},[demand]);useEffect(()=>{servicesRef.current=services;},[services]);useEffect(()=>{priorityRef.current=priorityPlatform;},[priorityPlatform]);useEffect(()=>{servedRef.current=served;},[served]);useEffect(()=>{departuresRef.current=departures;},[departures]);useEffect(()=>{lostRef.current=lost;},[lost]);useEffect(()=>{satRef.current=satisfaction;},[satisfaction]);useEffect(()=>{clockRef.current=clock;},[clock]);

  useEffect(()=>{setServices(prev=>{const next=[];for(let p=1;p<=platformsUnlocked;p++){const old=prev.find(s=>s.platform===p),fallback=unlockedRoutes[(p-1)%Math.max(1,unlockedRoutes.length)]?.id||'north';next.push(old&&unlockedRoutes.some(r=>r.id===old.routeId)?old:makeService(p,fallback,1));}servicesRef.current=next;return next;});if(priorityPlatform>platformsUnlocked)setPriorityPlatform(1);},[platformsUnlocked,effectiveLevel]);

  const addCash=(v)=>{cashRef.current+=v;setCash(Math.round(cashRef.current));};
  const spend=(v)=>{if(cashRef.current<v)return false;cashRef.current-=v;setCash(Math.round(cashRef.current));return true;};
  const changeSat=(v)=>{satRef.current=clamp(satRef.current+v,0,100);setSatisfaction(Math.round(satRef.current));};
  const awardDevelopment=(points)=>{let xp=developmentRef.current+points,lv=stationLevelRef.current,levelled=false;while(lv<MAX_STATION_LEVEL&&xp>=xpNeed(lv)){xp-=xpNeed(lv);lv+=1;levelled=true;}developmentRef.current=xp;stationLevelRef.current=lv;setDevelopmentXP(xp);setStationLevel(lv);if(levelled){setFlash(`STATION LEVEL ${lv}!`);setMessage(`${STAGES[lv-1][0]} unlocked. New station options are available.`);setTimeout(()=>setFlash(''),1700);}};
  const upgrade=(kind)=>{const spec=FACILITIES[kind];if(!spec||effectiveLevel<spec.unlock)return;const lv=levels[kind]||0;if(lv>=MAX_FACILITY_LEVEL)return;const price=upgradeCost(spec.base,lv);if(!spend(price)){setMessage(`${spec.title} costs ${money(price)}.`);return;}const next=lv+1,mile=milestone(kind,next),bonus=mile?Math.round(price*.18+next*25):0;setLevels(prev=>({...prev,[kind]:next}));levelsRef.current={...levelsRef.current,[kind]:next};if(bonus)addCash(bonus);awardDevelopment(mile?2:1);setMessage(mile?`${spec.title} Lv ${next}: ${mile} unlocked!`:`${spec.title} upgraded to Lv ${next}: ${effectFor(kind,next)}.`);setFlash(mile?`★ ${mile}${bonus?`  +${money(bonus)}`:''}`:`${spec.title.toUpperCase()} LV ${next}`);setTimeout(()=>setFlash(''),mile?1700:950);};
  const fixBottleneck=()=>upgrade(bottleneck[2]);
  const setSets=(platform,n)=>{if(n>maxSets)return;const next=servicesRef.current.map(s=>s.platform===platform&&!['ready','holding','departing'].includes(s.phase)?{...s,sets:n}:s);servicesRef.current=next;setServices(next);};
  const waitService=(platform)=>{const next=servicesRef.current.map(s=>s.platform===platform&&s.phase==='ready'?{...s,phase:'holding',hold:5}:s);servicesRef.current=next;setServices(next);setMessage(`P${platform}: doors reopened for 5 seconds.`);};
  const departService=(platform)=>{const current=servicesRef.current.find(s=>s.platform===platform);if(!current||current.phase!=='ready')return;const route=routeById(current.routeId),routeDemand={...demandRef.current},stranded=routeDemand[route.id]||0,quality=.85+satRef.current/100*.25,trainBonus=1+(Math.max(1,levelsRef.current.train)-1)*.06+(levelsRef.current.vip||0)*.015,gross=Math.round(current.onboard*route.fare*quality*trainBonus),operating=30*current.sets,bonus=current.delay<=3?160:current.delay<=8?70:0,payout=Math.max(0,gross-operating+bonus);addCash(payout);servedRef.current+=current.onboard;departuresRef.current+=1;setServed(servedRef.current);setDepartures(departuresRef.current);changeSat(-(Math.min(7,stranded*.025)+Math.max(0,current.delay-4)*.12)+(current.delay<=3?1:0));const next=servicesRef.current.map(s=>s.platform===platform?{...s,phase:'departing',countdown:2,delay:0,hold:0}:s);servicesRef.current=next;setServices(next);setMessage(`${route.name} departed with ${current.onboard}. Revenue ${money(payout)}.`);setFlash(`+${money(payout)}`);setTimeout(()=>setFlash(''),1100);};

  const goal=GOALS[Math.min(goalIndex,GOALS.length-1)],goalDone=goal[0]==='served'?served>=goal[1]:goal[0]==='departures'?departures>=goal[1]:goal[0]==='station'?stationLevel>=goal[1]:(levels[goal[0]]||0)>=goal[1];
  const claimGoal=()=>{if(!goalDone)return;addCash(goal[3]);setGoalIndex(v=>Math.min(GOALS.length-1,v+1));awardDevelopment(1);setFlash(`GOAL +${money(goal[3])}`);setMessage('Goal claimed. Keep developing the weakest link.');setTimeout(()=>setFlash(''),1400);};
  const persist=()=>saveGame({cash:cashRef.current,gems,levels:levelsRef.current,stationLevel:stationLevelRef.current,developmentXP:developmentRef.current,served:servedRef.current,departures:departuresRef.current,lost:lostRef.current,satisfaction:satRef.current,goalIndex});

  useEffect(()=>{if(phase!=='playing')return undefined;const id=setInterval(()=>{
    const lv=levelsRef.current;let pk=parkingRef.current,en=entranceRef.current,tk=ticketRef.current,se=securityRef.current,wa=waitingRef.current,routeDemand={...demandRef.current};const c=clockRef.current+1;clockRef.current=c;setClock(c);const rushNow=(c%90)>=70;
    const baseInflow=3+effectiveLevel*.65+Math.min(1.2,Math.max(0,lv.parking-1)*.08),inflow=Math.max(1,Math.round(baseInflow*(rushNow?1.6:1))),accepted=Math.min(inflow,Math.max(0,parkingCap-pk)),rejected=inflow-accepted;pk+=accepted;if(rejected>0){lostRef.current+=rejected;setLost(lostRef.current);changeSat(-Math.min(.6,rejected*.02));}
    const p2e=Math.min(pk,6+Math.max(1,lv.parking)*3,Math.max(0,entranceCap-en));pk-=p2e;en+=p2e;
    const e2t=Math.min(en,5+Math.max(1,lv.entrance)*3,Math.max(0,ticketCap-tk));en-=e2t;tk+=e2t;
    const t2s=Math.min(tk,5+Math.max(1,lv.ticket)*3,Math.max(0,securityCap-se));tk-=t2s;se+=t2s;
    const s2w=Math.min(se,4+Math.max(1,lv.security)*3,Math.max(0,waitingCap-wa));se-=s2w;wa+=s2w;
    const pTotal=Object.values(routeDemand).reduce((a,b)=>a+b,0),routing=6+Math.max(1,lv.waiting)*3+(lv.signage||0)*2+(platformsUnlocked-1)*4,toPlatform=Math.min(wa,routing,Math.max(0,platformCap-pTotal));wa-=toPlatform;for(let i=0;i<toPlatform;i++){const r=unlockedRoutes[(c+i+Math.floor(i/4))%Math.max(1,unlockedRoutes.length)];routeDemand[r.id]=(routeDemand[r.id]||0)+1;}
    let nextServices=servicesRef.current.map(x=>({...x}));nextServices=nextServices.map(service=>{const route=routeById(service.routeId);let ns={...service};if(['boarding','holding','ready'].includes(ns.phase)){const match=routeDemand[route.id]||0,priority=priorityRef.current===ns.platform?1.4:1,boardRate=Math.round((8+Math.max(1,lv.platform)*4+(lv.signage||0))*priority),capacity=trainCapacity(ns,lv,effectiveLevel),board=Math.min(match,boardRate,Math.max(0,capacity-ns.onboard));routeDemand[route.id]=match-board;ns.onboard+=board;}
      if(ns.phase==='arriving'){ns.countdown=Math.max(0,ns.countdown-1);if(ns.countdown<=0){ns.phase='boarding';ns.countdown=Math.max(12,22-effectiveLevel)+ns.platform*2;}}
      else if(ns.phase==='boarding'){ns.countdown=Math.max(0,ns.countdown-1);if(ns.countdown<=0){ns.phase='ready';ns.delay=0;setMessage(`P${ns.platform} ${route.name} is ready to depart.`);}}
      else if(ns.phase==='holding'){ns.hold=Math.max(0,ns.hold-1);ns.delay+=1;if(ns.hold<=0)ns.phase='ready';}
      else if(ns.phase==='ready'){ns.delay+=1;}
      else if(ns.phase==='departing'){ns.countdown=Math.max(0,ns.countdown-1);if(ns.countdown<=0){ns.phase='away';ns.countdown=5+ns.platform;ns.onboard=0;}}
      else if(ns.phase==='away'){ns.countdown=Math.max(0,ns.countdown-1);if(ns.countdown<=0){const idx=unlockedRoutes.findIndex(r=>r.id===ns.routeId),nextRoute=unlockedRoutes[(Math.max(0,idx)+platformsUnlocked)%Math.max(1,unlockedRoutes.length)]||unlockedRoutes[0]||ROUTES[0];ns={...ns,routeId:nextRoute.id,phase:'arriving',countdown:2,delay:0,hold:0,onboard:0};}}
      return ns;});
    const managerLv=lv.manager||0;if(managerLv>0){const threshold=Math.max(1,5-Math.floor(managerLv/3)),auto=nextServices.find(x=>x.phase==='ready'&&x.delay>=threshold);if(auto){servicesRef.current=nextServices;demandRef.current=routeDemand;setServices(nextServices);setDemand(routeDemand);setTimeout(()=>departService(auto.platform),20);}}
    const passive=(lv.cafe||0)*3+(lv.shop||0)*4+(lv.restaurant||0)*7+(lv.vip||0)*5;if(passive>0)addCash(passive);const ratios=[pk/parkingCap,en/entranceCap,tk/ticketCap,se/securityCap,wa/waitingCap,Object.values(routeDemand).reduce((a,b)=>a+b,0)/platformCap],worst=Math.max(...ratios),recovery=(lv.cleaning||0)*.012+(lv.toilet||0)*.007+(lv.signage||0)*.003;if(worst<.7)changeSat(.035+recovery);else if(worst>.98)changeSat(-.12+Math.min(.08,recovery));else if(recovery>0)changeSat(Math.min(.035,recovery));
    parkingRef.current=pk;entranceRef.current=en;ticketRef.current=tk;securityRef.current=se;waitingRef.current=wa;demandRef.current=routeDemand;servicesRef.current=nextServices;setParkingQ(pk);setEntranceQ(en);setTicketQ(tk);setSecurityQ(se);setWaitingQ(wa);setDemand(routeDemand);setServices(nextServices);if(c%15===0)persist();
  },TICK);return()=>clearInterval(id);},[phase,effectiveLevel,parkingCap,entranceCap,ticketCap,securityCap,waitingCap,platformCap,platformsUnlocked]);

  const visibleServices=useMemo(()=>services.filter(s=>s.platform<=platformsUnlocked),[services,platformsUnlocked]),occupiedCars=Math.min(30,Math.ceil(parkingQ/Math.max(1,parkingCap)*30)),readyCount=services.filter(s=>s.phase==='ready').length,alertOpacity=pulse.interpolate({inputRange:[0,1],outputRange:[.72,1]});
  if(phase==='menu')return <SafeAreaView style={styles.screen}><StatusBar barStyle="light-content"/><View style={styles.menu}><View style={styles.menuGlow}/><View style={styles.logo}><Text style={styles.logoSmall}>RAIL</Text><Text style={styles.logoBig}>RUSH HOUR</Text><View style={styles.logoLine}/></View><Text style={styles.version}>V0.29 • PROGRESSION & BALANCE</Text><Text style={styles.menuTitle}>MORE UPGRADES. BETTER FLOW.</Text><Text style={styles.menuCopy}>Parking no longer fills instantly. Every part of the station now has 15 upgrade levels and milestone unlocks.</Text><Pressable style={styles.start} onPress={()=>setPhase('playing')}><Text style={styles.startText}>OPEN STATION</Text></Pressable></View></SafeAreaView>;

  return <SafeAreaView style={styles.screen}><StatusBar barStyle="light-content"/><View style={styles.game}>
    <View style={styles.topHud}><HudTile label="STATION"><View style={styles.levelBadge}><Text style={styles.levelText}>{effectiveLevel}</Text></View></HudTile><HudTile label="CASH" wide><Text style={styles.cash}>{money(cash)}</Text><Text style={styles.smallGreen}>live income</Text></HudTile><HudTile label="GEMS"><Text style={styles.gems}>◆ {gems}</Text></HudTile><HudTile label="SATISFACTION"><Text style={[styles.sat,satisfaction<60&&styles.satBad]}>{satisfaction}%</Text><View style={styles.satBar}><View style={[styles.satFill,{width:`${satisfaction}%`}]} /></View></HudTile></View>
    <Animated.View style={[styles.alert,bottleneckPct>=90&&styles.alertHot,{opacity:bottleneckPct>=90?alertOpacity:1}]}><View style={styles.alertMark}><Text style={styles.alertMarkText}>!</Text></View><View style={{flex:1}}><Text style={styles.alertTitle}>CURRENT BOTTLENECK</Text><Text style={styles.alertText}>{bottleneck[0]} • {bottleneckPct}% capacity</Text></View><Pressable onPress={fixBottleneck} style={styles.fix}><Text style={styles.fixText}>UPGRADE</Text></Pressable></Animated.View>
    <View style={styles.development}><View style={styles.devTop}><Text style={styles.devTitle}>STATION DEVELOPMENT</Text><Text style={styles.devValue}>{developmentXP}/{xpRequired} XP → LEVEL {Math.min(MAX_STATION_LEVEL,stationLevel+1)}</Text></View><View style={styles.devTrack}><View style={[styles.devFill,{width:`${xpPct}%`}]} /></View></View>
    <View style={styles.serviceDeck}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.serviceInner}>{visibleServices.map(s=><ServiceCard key={s.platform} service={s} levels={levels} stationLevel={effectiveLevel} waiting={demand[s.routeId]||0} priority={priorityPlatform===s.platform} onPriority={()=>setPriorityPlatform(s.platform)} onWait={()=>waitService(s.platform)} onDepart={()=>departService(s.platform)}/>)}</ScrollView></View>

    <View style={styles.sceneArea}><View style={styles.scene}>
      <View style={styles.grass}/><View style={styles.railBed}/>{[1,2,3].map(n=>{const unlocked=n<=platformsUnlocked,service=services.find(s=>s.platform===n),route=service?routeById(service.routeId):ROUTES[n-1]||ROUTES[0],top=12+(n-1)*59,boarding=unlocked&&service&&['boarding','holding'].includes(service.phase);return <React.Fragment key={n}><View style={[styles.track,{top:top+4,opacity:unlocked?1:.16}]}><View style={styles.railOne}/><View style={styles.railTwo}/>{Array.from({length:18}).map((_,i)=><View key={i} style={[styles.tie,{left:i*21}]}/>)}</View><View style={[styles.platform,{top:top+26,opacity:unlocked?1:.25},service?.phase==='ready'&&styles.platformReady]}><View style={styles.platformEdge}/><View style={styles.yellowLine}/><View style={[styles.platformBadge,{backgroundColor:unlocked?route.color:'#777'}]}><Text style={styles.platformBadgeText}>{unlocked?`${route.code}${n}`:`P${n}`}</Text></View><View style={{flex:1}}><Text style={styles.platformName}>{unlocked?route.name:'LOCKED PLATFORM'}</Text><Text style={styles.platformInfo}>{unlocked?`${demand[route.id]||0} waiting`:`Unlock at Station ${n===2?4:8}`}</Text></View>{unlocked?<MiniPeople count={demand[route.id]||0} color={route.color}/>:null}{unlocked&&levels.platform>=3?<View style={[styles.canopy,{width:60+Math.min(55,levels.platform*4)}]}><View style={styles.canopyRoof}/><View style={styles.canopyPost}/></View>:null}</View>{unlocked&&service?<TrainGraphic service={service} top={top-1} pulse={pulse}/>:null}{boarding?<Flow active from={[235,258]} to={[270,top+35]} color={route.color} count={3}/>:null}</React.Fragment>;})}

      <View style={styles.station}><View style={styles.stationRoof}><Text style={styles.stationBrand}>RAIL RUSH HOUR</Text><Text style={styles.stationSub}>NORTHVALE • {stage[0].toUpperCase()}</Text>{levels.signage>0?<View style={styles.bigBoard}><Text style={styles.bigBoardText}>A1 NORTHBRIDGE • B2 SEABRIGHT • C3 EMBERFALL</Text></View>:null}</View><View style={styles.hall}>
        <View style={styles.zone}><Text style={styles.zoneTitle}>ENTRANCE</Text><Text style={styles.zoneCount}>{entranceQ}/{entranceCap}</Text><MiniPeople count={entranceQ} color="#75a7c4"/><View style={styles.gateRow}>{Array.from({length:Math.min(6,1+Math.floor(levels.entrance/2))}).map((_,i)=><View key={i} style={styles.entryGate}/>)}</View></View>
        <View style={styles.zone}><Text style={styles.zoneTitle}>TICKETS</Text><Text style={styles.zoneCount}>{ticketQ}/{ticketCap}</Text><MiniPeople count={ticketQ} color="#d8a94e"/><View style={styles.gateRow}>{Array.from({length:Math.min(6,1+Math.floor(levels.ticket/2))}).map((_,i)=><View key={i} style={styles.ticketMachine}/>)}</View></View>
        <View style={styles.zone}><Text style={styles.zoneTitle}>SECURITY</Text><Text style={styles.zoneCount}>{securityQ}/{securityCap}</Text><MiniPeople count={securityQ} color="#dc7769"/><View style={styles.gateRow}>{Array.from({length:Math.min(6,1+Math.floor(levels.security/2))}).map((_,i)=><View key={i} style={styles.securityGate}/>)}</View></View>
        <View style={[styles.zone,styles.waitZone]}><Text style={styles.zoneTitle}>WAITING</Text><Text style={styles.zoneCount}>{waitingQ}/{waitingCap}</Text><MiniPeople count={waitingQ} color="#58a9cf"/><View style={styles.seats}>{Array.from({length:Math.min(10,3+Math.floor(levels.waiting/2))}).map((_,i)=><View key={i} style={styles.seat}/>)}</View></View>
      </View><View style={styles.facade}><Text style={styles.facadeTitle}>NORTHVALE STATION</Text><View style={styles.glassDoors}>{Array.from({length:Math.min(5,1+Math.floor(levels.entrance/3))}).map((_,i)=><View key={i} style={styles.glassDoor}/>)}</View><Text style={styles.facadeSub}>PARKING → ENTRANCE → TICKETS → SECURITY → PLATFORMS</Text></View></View>

      <View style={styles.servicesStrip}><Text style={styles.servicesText}>☕{levels.cafe}  ▦{levels.shop}  ✦{levels.cleaning}  WC{levels.toilet}  🍴{levels.restaurant}  ★{levels.vip}</Text></View>
      <View style={[styles.parking,{height:levels.parking>=6?77:66}]}><View style={styles.parkingHead}><Text style={styles.parkingTitle}>P  PARKING • LV {levels.parking}</Text><Text style={styles.parkingCount}>{parkingQ}/{parkingCap}</Text></View>{levels.parking>=6?<View style={styles.parkingTier}><Text style={styles.parkingTierText}>{levels.parking>=12?'PARKING DECK':levels.parking>=9?'COVERED PARKING':'P+R ZONE'}</Text></View>:null}<View style={styles.parkingGrid}>{Array.from({length:30}).map((_,i)=><View key={i} style={styles.space}>{i<occupiedCars?<View style={[styles.car,{backgroundColor:['#4aa9ff','#ef6b62','#f5c95c','#61c788','#9b8ee5'][i%5]}]}/>:null}</View>)}</View></View><View style={styles.road}><View style={styles.roadLine}/><View style={styles.crossing}>{Array.from({length:5}).map((_,i)=><View key={i} style={styles.crossStripe}/>)}</View></View>
      <Flow active={parkingQ>0} from={[110,390]} to={[155,347]} count={5}/><Flow active={entranceQ>0} from={[155,347]} to={[118,259]} count={4}/><Flow active={ticketQ>0} from={[118,259]} to={[170,258]} count={4}/><Flow active={securityQ>0} from={[170,258]} to={[220,258]} count={4}/><Flow active={waitingQ>0} from={[220,258]} to={[258,255]} count={4}/>

      <View style={styles.sideMenu}><SideButton icon="✓" label="GOALS" badge={goalDone?'1':null} active={panel==='goals'} onPress={()=>setPanel(panel==='goals'?null:'goals')}/><SideButton icon="↯" label="FLOW" active={panel==='flow'} onPress={()=>setPanel(panel==='flow'?null:'flow')}/><SideButton icon="↑" label="LEVELS" active={panel==='levels'} onPress={()=>setPanel(panel==='levels'?null:'levels')}/></View><View style={[styles.rush,rush&&styles.rushOn]}><Text style={styles.rushText}>{rush?'⚡ RUSH +60%':'NORMAL FLOW'}</Text></View><View style={styles.message}><Text style={styles.messageText}>{message}</Text></View>{flash?<Animated.View style={[styles.flash,{opacity:alertOpacity}]}><Text style={styles.flashText}>{flash}</Text></Animated.View>:null}

      {panel==='goals'?<Panel title="GOALS" onClose={()=>setPanel(null)}><Text style={styles.panelLead}>{goal[2]}</Text><Text style={styles.panelReward}>Reward {money(goal[3])} + 1 development XP</Text><Pressable disabled={!goalDone} onPress={claimGoal} style={[styles.claim,goalDone&&styles.claimReady]}><Text style={styles.claimText}>{goalDone?'CLAIM':'IN PROGRESS'}</Text></Pressable><View style={styles.divider}/>{GOALS.map((g,i)=><Text key={i} style={[styles.goalLine,i<goalIndex&&styles.goalDone]}>{i<goalIndex?'✓ ':i===goalIndex?'› ':'  '}{g[2]}</Text>)}</Panel>:null}
      {panel==='flow'?<Panel title="PASSENGER FLOW" onClose={()=>setPanel(null)}>{pressures.map(p=><View key={p[0]} style={styles.flowRow}><Text style={styles.flowName}>{p[0]}</Text><View style={styles.flowTrack}><View style={[styles.flowFill,{width:`${Math.min(100,Math.round(p[1]*100))}%`},p[1]>.9&&styles.flowHot]}/></View><Text style={styles.flowPct}>{Math.round(p[1]*100)}%</Text></View>)}<Text style={styles.panelLead}>Lost visitors: {lost}</Text><Text style={styles.panelNote}>Parking upgrades now add capacity and exit flow without aggressively increasing demand.</Text></Panel>:null}
      {panel==='levels'?<Panel title="STATION LEVELS" onClose={()=>setPanel(null)}><ScrollView style={{maxHeight:210}}>{STAGES.map((s,i)=><Pressable key={i} onPress={()=>setDevLevel(i+1)} style={[styles.levelRow,effectiveLevel===i+1&&styles.levelRowOn]}><Text style={styles.levelRowTitle}>LEVEL {i+1} • {s[0]}</Text><Text style={styles.levelRowSub}>{s[1]}</Text></Pressable>)}</ScrollView><View style={styles.devBtns}><Pressable style={styles.devBtn} onPress={()=>setDevLevel(v=>Math.max(1,(v??stationLevel)-1))}><Text style={styles.devBtnText}>−</Text></Pressable><Pressable style={styles.devLive} onPress={()=>setDevLevel(null)}><Text style={styles.devBtnText}>LIVE</Text></Pressable><Pressable style={styles.devBtn} onPress={()=>setDevLevel(v=>Math.min(10,(v??stationLevel)+1))}><Text style={styles.devBtnText}>+</Text></Pressable></View><View style={styles.trainLength}><Text style={styles.trainLengthTitle}>TRAIN LENGTH</Text>{visibleServices.map(s=><View key={s.platform} style={styles.setRow}><Text style={styles.setLabel}>P{s.platform}</Text>{[1,2,3].map(n=><Pressable key={n} disabled={n>maxSets} onPress={()=>setSets(s.platform,n)} style={[styles.setBtn,s.sets===n&&styles.setBtnOn,n>maxSets&&styles.setBtnLocked]}><Text style={styles.setText}>{n}</Text></Pressable>)}</View>)}</View></Panel>:null}
    </View></View>

    <View style={styles.upgradeDock}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.upgradeInner}>{Object.keys(FACILITIES).map(kind=><UpgradeCard key={kind} kind={kind} level={levels[kind]||0} stationLevel={effectiveLevel} cash={cash} hot={bottleneck[2]===kind} onPress={()=>upgrade(kind)}/>)}</ScrollView></View>
    <View style={styles.footer}><View style={styles.footerItem}><Text style={styles.footerLabel}>TRANSPORTED</Text><Text style={styles.footerValue}>{served.toLocaleString('nl-NL')}</Text></View><View style={styles.footerSplit}/><View style={styles.footerItem}><Text style={styles.footerLabel}>DEPARTURES</Text><Text style={styles.footerValue}>{departures}</Text></View><View style={styles.footerSplit}/><View style={styles.footerItem}><Text style={styles.footerLabel}>ACTIVE PLATFORMS</Text><Text style={styles.footerValue}>{platformsUnlocked}/3</Text></View>{readyCount>0?<View style={styles.readyBadge}><Text style={styles.readyBadgeText}>{readyCount} READY</Text></View>:null}</View>
  </View></SafeAreaView>;
}

const styles=StyleSheet.create({
  screen:{flex:1,backgroundColor:'#071119'},game:{flex:1,backgroundColor:'#0b1821'},menu:{flex:1,backgroundColor:'#0a1822',alignItems:'center',justifyContent:'center',padding:28,overflow:'hidden'},menuGlow:{position:'absolute',top:-80,width:420,height:250,borderRadius:210,backgroundColor:'#15394d',opacity:.55},logo:{width:225,paddingVertical:20,borderRadius:28,backgroundColor:'#132b39',borderWidth:2,borderColor:'#3d6b80',alignItems:'center'},logoSmall:{color:'#85d6ef',fontSize:17,fontWeight:'900',letterSpacing:8},logoBig:{color:'#fff',fontSize:31,fontWeight:'900'},logoLine:{width:145,height:4,borderRadius:2,backgroundColor:'#58d18b',marginTop:9},version:{color:'#6692a5',fontSize:9,fontWeight:'900',letterSpacing:2,marginTop:22},menuTitle:{color:'#f5cf69',fontSize:20,fontWeight:'900',marginTop:18,textAlign:'center'},menuCopy:{color:'#a9c0ca',fontSize:13,lineHeight:20,textAlign:'center',maxWidth:360,marginTop:11},start:{backgroundColor:'#65cf54',borderRadius:14,paddingVertical:16,paddingHorizontal:52,marginTop:28,borderWidth:2,borderColor:'#91ed75'},startText:{color:'#102318',fontSize:14,fontWeight:'900'},
  topHud:{height:69,backgroundColor:'#08131c',flexDirection:'row',padding:5,gap:4,borderBottomWidth:1,borderBottomColor:'#243542'},hudTile:{flex:1,minWidth:68,backgroundColor:'#14222e',borderRadius:10,borderWidth:1,borderColor:'#344652',padding:6,justifyContent:'center'},hudWide:{flex:1.35},hudLabel:{color:'#8aa0aa',fontSize:5.4,fontWeight:'900'},levelBadge:{width:34,height:34,borderRadius:9,backgroundColor:'#20384a',borderWidth:2,borderColor:'#67b9e4',alignItems:'center',justifyContent:'center',marginTop:2},levelText:{color:'#fff',fontSize:18,fontWeight:'900'},cash:{color:'#56e36e',fontSize:14,fontWeight:'900'},smallGreen:{color:'#67c97b',fontSize:5.2,fontWeight:'800'},gems:{color:'#d88cff',fontSize:12,fontWeight:'900'},sat:{color:'#70e28b',fontSize:13,fontWeight:'900'},satBad:{color:'#ff735f'},satBar:{height:5,backgroundColor:'#283a44',borderRadius:3,marginTop:4,overflow:'hidden'},satFill:{height:'100%',backgroundColor:'#67db66'},
  alert:{height:47,backgroundColor:'#2d2818',marginHorizontal:6,marginTop:5,borderRadius:10,borderWidth:1,borderColor:'#6f5d26',paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:8},alertHot:{backgroundColor:'#412218',borderColor:'#b76238'},alertMark:{width:27,height:27,borderRadius:14,backgroundColor:'#f5be38',alignItems:'center',justifyContent:'center'},alertMarkText:{color:'#3b2a07',fontSize:17,fontWeight:'900'},alertTitle:{color:'#f5cd69',fontSize:6.7,fontWeight:'900'},alertText:{color:'#eadbbf',fontSize:6.1,fontWeight:'800',marginTop:2},fix:{backgroundColor:'#f0ab24',paddingHorizontal:11,paddingVertical:8,borderRadius:7},fixText:{color:'#2b2008',fontSize:6,fontWeight:'900'},
  development:{height:35,backgroundColor:'#0e1d27',marginHorizontal:6,marginTop:4,borderRadius:8,borderWidth:1,borderColor:'#2b4655',paddingHorizontal:8,paddingVertical:5},devTop:{flexDirection:'row',justifyContent:'space-between'},devTitle:{color:'#83a7b8',fontSize:5.5,fontWeight:'900'},devValue:{color:'#d6edf5',fontSize:5.4,fontWeight:'900'},devTrack:{height:7,backgroundColor:'#243a46',borderRadius:4,overflow:'hidden',marginTop:4},devFill:{height:'100%',backgroundColor:'#65c982'},
  serviceDeck:{height:98,paddingTop:5,backgroundColor:'#0b1821'},serviceInner:{paddingHorizontal:6,gap:6},serviceCard:{width:174,height:88,backgroundColor:'#14232d',borderRadius:11,borderWidth:1,borderColor:'#354b58',borderTopWidth:4,padding:7},serviceReady:{backgroundColor:'#30281b'},serviceHead:{flexDirection:'row',alignItems:'center',gap:6},routeBadge:{width:30,height:30,borderRadius:7,alignItems:'center',justifyContent:'center'},routeBadgeText:{color:'#fff',fontSize:10,fontWeight:'900'},serviceName:{color:'#edf5f7',fontSize:7.4,fontWeight:'900'},serviceState:{color:'#8ca4ae',fontSize:5.4,fontWeight:'800',marginTop:2},readyText:{color:'#ffd16a'},priority:{width:24,height:24,borderRadius:7,backgroundColor:'#243742',alignItems:'center',justifyContent:'center'},priorityOn:{backgroundColor:'#e0ac31'},priorityText:{color:'#fff',fontSize:11,fontWeight:'900'},metaRow:{flexDirection:'row',justifyContent:'space-between',marginTop:5},metaText:{color:'#91a8b1',fontSize:5,fontWeight:'800'},progress:{height:5,backgroundColor:'#253944',borderRadius:3,overflow:'hidden',marginTop:4},progressFill:{height:'100%'},actions:{flexDirection:'row',gap:4,marginTop:4},waitBtn:{flex:1,backgroundColor:'#b77b2b',paddingVertical:4,borderRadius:5,alignItems:'center'},departBtn:{flex:1.3,backgroundColor:'#49ad68',paddingVertical:4,borderRadius:5,alignItems:'center'},actionText:{color:'#fff',fontSize:5,fontWeight:'900'},
  sceneArea:{flex:1,minHeight:310,backgroundColor:'#10212a',alignItems:'center',justifyContent:'center',overflow:'hidden'},scene:{width:390,height:425,backgroundColor:'#8dbb6c',position:'relative',overflow:'hidden'},grass:{position:'absolute',inset:0,backgroundColor:'#91bd72'},railBed:{position:'absolute',left:40,right:-25,top:0,height:183,backgroundColor:'#5d666a',transform:[{rotateZ:'-2deg'}]},track:{position:'absolute',left:53,width:360,height:34,backgroundColor:'#515a5e',transform:[{rotateZ:'-2deg'}]},railOne:{position:'absolute',left:0,right:0,top:8,height:3,backgroundColor:'#d3d8da'},railTwo:{position:'absolute',left:0,right:0,top:24,height:3,backgroundColor:'#d3d8da'},tie:{position:'absolute',top:4,width:5,height:27,backgroundColor:'#5a4435'},platform:{position:'absolute',left:69,width:308,height:34,backgroundColor:'#d8d3c6',borderRadius:5,borderWidth:1,borderColor:'#eee7d8',paddingHorizontal:5,flexDirection:'row',alignItems:'center',gap:5},platformReady:{borderColor:'#ffd15a',borderWidth:2},platformEdge:{position:'absolute',left:0,right:0,bottom:0,height:5,backgroundColor:'#9d9990'},yellowLine:{position:'absolute',left:5,right:5,top:4,height:3,borderRadius:2,backgroundColor:'#e7c94c'},platformBadge:{width:27,height:22,borderRadius:4,alignItems:'center',justifyContent:'center',zIndex:4},platformBadgeText:{color:'#fff',fontSize:8.5,fontWeight:'900'},platformName:{color:'#314b56',fontSize:6.2,fontWeight:'900'},platformInfo:{color:'#74878e',fontSize:4.7,fontWeight:'800'},peopleRow:{flexDirection:'row',gap:2,flexWrap:'wrap',alignItems:'flex-end',maxWidth:70},person:{width:6,height:11,alignItems:'center'},personHead:{width:4,height:4,borderRadius:2,backgroundColor:'#f0c49d'},personBody:{width:5,height:6,borderRadius:1,marginTop:1},canopy:{position:'absolute',right:57,top:5,height:17},canopyRoof:{position:'absolute',left:0,right:0,top:0,height:6,borderRadius:2,backgroundColor:'#426c7d',borderWidth:1,borderColor:'#8eb5c2'},canopyPost:{position:'absolute',left:'50%',top:6,width:2,height:11,backgroundColor:'#687d85'},
  trainWrap:{position:'absolute',left:112,height:32,zIndex:12},trainShadow:{position:'absolute',left:2,top:20,height:15,borderRadius:9,backgroundColor:'rgba(15,25,31,.3)'},trainBody:{height:27,backgroundColor:'#edf3f4',borderRadius:11,borderWidth:2,position:'relative',overflow:'visible'},trainNose:{position:'absolute',left:-1,top:-1,bottom:-1,width:29,borderTopLeftRadius:10,borderBottomLeftRadius:10},cabGlass:{position:'absolute',left:8,top:4,width:15,height:8,borderRadius:3,backgroundColor:'#143746',borderWidth:1,borderColor:'#6fa5ba'},routeStripe:{position:'absolute',left:28,right:0,bottom:4,height:3},carJoint:{position:'absolute',top:1,bottom:1,width:2,backgroundColor:'#a8b5ba'},carWindow:{position:'absolute',top:5,width:12,height:7,borderRadius:2,backgroundColor:'#2c586a',borderWidth:1,borderColor:'#74a6b8'},doorSlot:{position:'absolute',top:3,width:12,height:18},doorPocket:{width:12,height:18,position:'relative'},doorLeaf:{position:'absolute',left:0,top:0,width:6,height:18,borderRadius:1,backgroundColor:'#c6d9df',borderWidth:1,borderColor:'#6f8992'},bogie:{position:'absolute',bottom:-6,width:13,height:8,borderRadius:5,backgroundColor:'#25373e',borderWidth:2,borderColor:'#5f7077'},trainRoof:{position:'absolute',left:42,right:15,top:1,height:2,borderRadius:1,backgroundColor:'#b6c3c8'},movingDot:{position:'absolute',left:0,top:0,width:6,height:6,borderRadius:3,zIndex:60},
  station:{position:'absolute',left:66,top:190,width:313,height:144,backgroundColor:'#dfdbcf',borderRadius:8,borderWidth:2,borderColor:'#596f78'},stationRoof:{height:39,backgroundColor:'#294c5b',borderTopLeftRadius:6,borderTopRightRadius:6,paddingHorizontal:8,paddingTop:5},stationBrand:{color:'#fff',fontSize:9,fontWeight:'900'},stationSub:{color:'#9fc4d2',fontSize:4.6,fontWeight:'800',marginTop:1},bigBoard:{position:'absolute',right:7,top:6,width:135,height:23,backgroundColor:'#0e1b21',borderRadius:3,borderWidth:1,borderColor:'#48606b',justifyContent:'center',paddingHorizontal:4},bigBoardText:{color:'#f4c74e',fontSize:3.5,fontWeight:'900'},hall:{position:'absolute',left:6,right:6,top:44,bottom:28,backgroundColor:'#f0ede5',borderRadius:5,flexDirection:'row',gap:3,padding:4},zone:{flex:1,backgroundColor:'#f4eadc',borderRadius:4,borderWidth:1,borderColor:'#cbbda7',padding:3},waitZone:{flex:1.15,backgroundColor:'#e7efe7',borderColor:'#8aad97'},zoneTitle:{color:'#38515a',fontSize:4.4,fontWeight:'900'},zoneCount:{color:'#72838a',fontSize:4,fontWeight:'800'},gateRow:{position:'absolute',left:3,right:3,bottom:3,flexDirection:'row',gap:2},entryGate:{width:6,height:15,borderRadius:2,backgroundColor:'#6a9ab1',borderTopWidth:3,borderTopColor:'#a7d3e4'},ticketMachine:{width:6,height:15,borderRadius:2,backgroundColor:'#c69a4f',borderTopWidth:3,borderTopColor:'#4d6b78'},securityGate:{width:7,height:15,borderWidth:2,borderBottomWidth:4,borderColor:'#6d797d',borderRadius:2},seats:{position:'absolute',left:3,right:3,bottom:3,flexDirection:'row',flexWrap:'wrap',gap:2},seat:{width:12,height:5,borderRadius:2,backgroundColor:'#527f9a'},facade:{position:'absolute',left:58,right:58,bottom:-27,height:44,backgroundColor:'#d7d4ca',borderWidth:2,borderColor:'#536b76',borderRadius:5,alignItems:'center',justifyContent:'center'},facadeTitle:{color:'#304b57',fontSize:6.8,fontWeight:'900'},glassDoors:{height:14,flexDirection:'row',gap:2,marginTop:2},glassDoor:{width:15,height:14,backgroundColor:'#6da6ba',borderWidth:1,borderColor:'#d6eef4'},facadeSub:{color:'#7b898d',fontSize:3.5,fontWeight:'800',marginTop:2},servicesStrip:{position:'absolute',left:76,top:337,width:297,height:25,backgroundColor:'#e2d7c4',borderRadius:5,borderWidth:1,borderColor:'#b8a88d',alignItems:'center',justifyContent:'center'},servicesText:{color:'#705c47',fontSize:6.2,fontWeight:'900'},
  parking:{position:'absolute',left:8,top:350,width:195,backgroundColor:'#58666b',borderRadius:6,borderWidth:2,borderColor:'#c6d0d2',padding:4},parkingHead:{flexDirection:'row',justifyContent:'space-between'},parkingTitle:{color:'#fff',fontSize:5.3,fontWeight:'900'},parkingCount:{color:'#d5e4e7',fontSize:5,fontWeight:'900'},parkingTier:{position:'absolute',right:4,top:17,backgroundColor:'#2b444f',borderRadius:3,paddingHorizontal:4,paddingVertical:2,zIndex:3},parkingTierText:{color:'#bfe4ef',fontSize:3.8,fontWeight:'900'},parkingGrid:{flexDirection:'row',flexWrap:'wrap',gap:2,marginTop:4},space:{width:17,height:8,borderWidth:1,borderColor:'#aebabc',alignItems:'center',justifyContent:'center'},car:{width:11,height:4,borderRadius:2},road:{position:'absolute',left:201,top:365,width:200,height:49,backgroundColor:'#596267',transform:[{rotateZ:'-4deg'}],borderRadius:6},roadLine:{position:'absolute',left:0,right:0,top:24,height:2,backgroundColor:'#e0d9c1'},crossing:{position:'absolute',left:14,top:6,flexDirection:'row',gap:3},crossStripe:{width:6,height:28,backgroundColor:'#e6e4dc'},
  sideMenu:{position:'absolute',left:5,top:54,gap:4,zIndex:80},sideBtn:{width:57,height:46,borderRadius:8,backgroundColor:'rgba(10,28,38,.95)',borderWidth:1,borderColor:'#385365',alignItems:'center',justifyContent:'center'},sideBtnOn:{backgroundColor:'#254e63',borderColor:'#6bb9de'},sideIcon:{color:'#e9f3f7',fontSize:13,fontWeight:'900'},sideLabel:{color:'#b8ccd5',fontSize:4.7,fontWeight:'900',marginTop:2},sideBadge:{position:'absolute',right:-3,top:-3,width:15,height:15,borderRadius:8,backgroundColor:'#ed5d51',alignItems:'center',justifyContent:'center'},sideBadgeText:{color:'#fff',fontSize:7,fontWeight:'900'},rush:{position:'absolute',right:7,top:5,backgroundColor:'rgba(13,36,47,.94)',borderRadius:8,paddingHorizontal:8,paddingVertical:5,borderWidth:1,borderColor:'#46697a',zIndex:80},rushOn:{backgroundColor:'#7a3c1f',borderColor:'#f0a44f'},rushText:{color:'#d9e7ec',fontSize:5.3,fontWeight:'900'},message:{position:'absolute',left:72,right:8,bottom:5,backgroundColor:'rgba(8,27,36,.93)',borderRadius:7,borderWidth:1,borderColor:'#3b6171',paddingHorizontal:7,paddingVertical:5,zIndex:80},messageText:{color:'#c1d4dc',fontSize:5.2,fontWeight:'800'},flash:{position:'absolute',left:105,right:48,top:178,backgroundColor:'rgba(22,70,43,.96)',borderRadius:9,borderWidth:1,borderColor:'#68de91',paddingVertical:8,alignItems:'center',zIndex:90},flashText:{color:'#e3ffed',fontSize:7,fontWeight:'900'},
  upgradeDock:{height:132,backgroundColor:'#08151d',borderTopWidth:1,borderTopColor:'#243944'},upgradeInner:{paddingHorizontal:6,paddingVertical:5,gap:5},upgradeCard:{width:118,height:121,backgroundColor:'#152630',borderRadius:10,borderWidth:1,borderColor:'#38505d',padding:6,alignItems:'center'},upgradeHot:{borderColor:'#f1c451',borderWidth:2},upgradeMilestone:{backgroundColor:'#2b291e',borderColor:'#b48b35'},locked:{opacity:.5},upIcon:{width:28,height:28,borderRadius:8,backgroundColor:'#263c48',alignItems:'center',justifyContent:'center'},upIconText:{color:'#d9edf3',fontSize:11,fontWeight:'900'},upTitle:{color:'#edf5f7',fontSize:6.3,fontWeight:'900',marginTop:3},upLevel:{color:'#8ea7b1',fontSize:5,fontWeight:'900',marginTop:1},upEffect:{color:'#62d986',fontSize:4.7,fontWeight:'800',marginTop:2},nextMilestone:{color:'#768f9a',fontSize:4.2,fontWeight:'800',marginTop:2,textAlign:'center'},nextMilestoneNow:{color:'#f3ca68'},buyBtn:{position:'absolute',left:6,right:6,bottom:5,height:24,borderRadius:6,backgroundColor:'#263842',alignItems:'center',justifyContent:'center'},buyReady:{backgroundColor:'#55b927',borderWidth:1,borderColor:'#7de14c'},buyMilestone:{backgroundColor:'#d89e2f',borderColor:'#ffd56b'},buyText:{color:'#fff',fontSize:6.2,fontWeight:'900'},
  footer:{height:42,backgroundColor:'#08131b',borderTopWidth:1,borderTopColor:'#29414e',flexDirection:'row',alignItems:'center',paddingHorizontal:7,gap:7},footerItem:{flex:1},footerLabel:{color:'#6f8a96',fontSize:4.4,fontWeight:'900'},footerValue:{color:'#edf6f8',fontSize:8,fontWeight:'900',marginTop:1},footerSplit:{width:1,height:24,backgroundColor:'#2a414d'},readyBadge:{backgroundColor:'#d69c28',borderRadius:5,paddingHorizontal:6,paddingVertical:4},readyBadgeText:{color:'#fff',fontSize:5,fontWeight:'900'},
  panelShade:{position:'absolute',left:64,right:7,top:48,bottom:34,backgroundColor:'rgba(6,17,23,.52)',zIndex:110,alignItems:'center',justifyContent:'center'},panel:{width:'94%',maxHeight:'92%',backgroundColor:'#edf0e8',borderRadius:12,borderWidth:2,borderColor:'#436678',padding:10},panelHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},panelTitle:{color:'#2c4a57',fontSize:12,fontWeight:'900'},close:{width:28,height:28,borderRadius:7,backgroundColor:'#d5d8d1',alignItems:'center',justifyContent:'center'},closeText:{color:'#47616b',fontSize:18,fontWeight:'900'},panelLead:{color:'#3c5a65',fontSize:8,fontWeight:'900',marginTop:10},panelReward:{color:'#a47725',fontSize:7.5,fontWeight:'900',marginTop:5},panelNote:{color:'#74868c',fontSize:6,lineHeight:9,marginTop:10},claim:{marginTop:10,backgroundColor:'#9aa5a1',paddingVertical:9,borderRadius:8,alignItems:'center'},claimReady:{backgroundColor:'#50b975'},claimText:{color:'#fff',fontSize:7,fontWeight:'900'},divider:{height:1,backgroundColor:'#c9cec5',marginVertical:10},goalLine:{color:'#738187',fontSize:6.2,fontWeight:'800',marginVertical:3},goalDone:{color:'#4d9a68'},flowRow:{flexDirection:'row',alignItems:'center',gap:6,paddingVertical:6},flowName:{width:66,color:'#38535e',fontSize:5.8,fontWeight:'900'},flowTrack:{flex:1,height:8,backgroundColor:'#d0d4cb',borderRadius:4,overflow:'hidden'},flowFill:{height:'100%',backgroundColor:'#55afd2'},flowHot:{backgroundColor:'#e56d59'},flowPct:{width:28,textAlign:'right',color:'#5f737b',fontSize:5.8,fontWeight:'900'},levelRow:{padding:7,borderBottomWidth:1,borderBottomColor:'#cdd1c8'},levelRowOn:{backgroundColor:'#fff0ba'},levelRowTitle:{color:'#34515d',fontSize:6.8,fontWeight:'900'},levelRowSub:{color:'#7a898e',fontSize:5.3,marginTop:2},devBtns:{flexDirection:'row',gap:6,justifyContent:'center',marginTop:8},devBtn:{width:38,height:29,borderRadius:7,backgroundColor:'#456775',alignItems:'center',justifyContent:'center'},devLive:{width:60,height:29,borderRadius:7,backgroundColor:'#456775',alignItems:'center',justifyContent:'center'},devBtnText:{color:'#fff',fontSize:7,fontWeight:'900'},trainLength:{marginTop:8,paddingTop:7,borderTopWidth:1,borderTopColor:'#cbd0c7'},trainLengthTitle:{color:'#38535e',fontSize:6.5,fontWeight:'900'},setRow:{flexDirection:'row',alignItems:'center',gap:5,marginVertical:3},setLabel:{width:26,color:'#38535e',fontSize:6.5,fontWeight:'900'},setBtn:{width:28,height:23,borderRadius:5,backgroundColor:'#cdd3cf',alignItems:'center',justifyContent:'center'},setBtnOn:{backgroundColor:'#69c98a'},setBtnLocked:{opacity:.3},setText:{color:'#2e4b56',fontSize:7,fontWeight:'900'},
});
